# Generated by Django 3.2.11 on 2022-01-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='Conversion_Code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='Target_ActualCode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='Target_Expected_Output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='Target_FeatureDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
