# Generated by Django 4.0 on 2022-01-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='Conversion_Description',
        ),
        migrations.AddField(
            model_name='feature',
            name='Feature_Version',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feature',
            name='Level',
            field=models.CharField(blank=True, choices=[('Programlevel', 'programlevel'), ('Statementlevel', 'statementlevel')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='Sequence_Number',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
