# Generated by Django 4.0 on 2022-01-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='Migration_TypeId',
            field=models.CharField(choices=[('1', 'oracle'), ('2', 'ssql'), ('3', 'mysql')], default='oracle', max_length=50),
        ),
    ]
