# Generated by Django 4.0 on 2022-01-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_alter_feature_migration_typeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='Feature_Id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
