# Generated by Django 3.2.10 on 2022-01-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0003_alter_feature_feature_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='Migration_TypeId',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='feature',
            name='Object_Type',
            field=models.CharField(max_length=50),
        ),
    ]
