# Generated by Django 4.0 on 2022-01-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0006_alter_upload_file_feature_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='Feature_Version',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feature',
            name='Level',
            field=models.CharField(blank=True, choices=[('Programlevel', 'programlevel'), ('Statementlevel', 'statementlevel')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='Sequence_Number',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='Feature_Name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='Version_Id',
            field=models.SmallIntegerField(default=0),
        ),
    ]
